name: build-workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Build nitro image
        run: |
          mkdir artifact
          docker build --tag builder:latest .
          docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/usr/bin/docker -v ./artifact/:/artifact builder:latest
          ls -alh artifact/
